name: lint
on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        name: Install Python
        with:
          python-version: '3.8'
      - name: Install Dependencies
        run: pip install black isort

      - name: Lint Python Code
        uses: actions/github-script@v6.4.1
        run: |
          black --check pynixify
          isort --check pynixify
