name: "Test"
on:
  pull_request:
  push:
jobs:
  nixos-20-09:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-20.09
    - run: nix-build
    - run: nix-shell --command 'pytest -v tests/ acceptance_tests'
    - run: |
        nix-env -if default.nix && nix-shell -p bats --command './acceptance_tests/test_command.sh'
  nixos-21-05:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-21.05
    - run: nix-build
    - run: nix-shell --command 'pytest -v tests/ acceptance_tests'
    - run: |
        nix-env -if default.nix && nix-shell -p bats --command './acceptance_tests/test_command.sh'
  nixos-unstable:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix-build --arg runMypy false  # TODO run mypy in unstable
    - run: nix-shell --command 'pytest -v tests/ acceptance_tests'
    - run: |
        nix-env -if default.nix --arg runMypy false && nix-shell -p bats --command './acceptance_tests/test_command.sh'  # TODO run mypy in unstable
